name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Android SDK
        uses: reactivecircus/setup-android@v2
        with:
          components: build-tools-28.0.3

      - name: Set up ANDROID_HOME
        run: echo "ANDROID_HOME=${{ runner.workspace }}/.android" >> $GITHUB_ENV

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ANDROID_HOME: ${{ runner.workspace }}/.android
        with:
          args: --fail-on=all
