name: Source Composition Analysis Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8' # or '11' if you prefer
          distribution: 'temurin' # Eclipse Temurin is a widely used distribution

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-platform: '29' # set to your target SDK version
          ndk-version: '21.4.7075529' # set to your desired NDK version

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Set up ANDROID_HOME
        run: echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=all
