name: Source Composition Analysis Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8' # or '11' if you prefer
          distribution: 'temurin' # Eclipse Temurin is a widely used distribution

      - uses: actions/setup-java@v2
        with:
          java-version: '8' # or '11' if you prefer
          distribution: 'temurin' # Eclipse Temurin is a widely used distribution
          path: ${{ env.JAVA_HOME }}

      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=all
